### ISSUE TITLE
Translate action of a particular controller

### ISSUE THREAD

**Issue by jhonathas** [enriclluelles/route_translator#128]
I can translate an action of a controller in particular.

Something like

```
routes:
    home: pagina_inicial
    contacts: contato
    new: novo
    makers:
        new: adicionar
```
