### ISSUE TITLE
Namespace route not working

### ISSUE THREAD

**Issue by musixite** [enriclluelles/route_translator#150]
I'm using namespaces and I'd like to achieve the following routes:
English:
localhost:3000/in-the-studio

French:
localhost:3000/fr/en-studio

pages_controller
```
module Testing
	class PagesController < BaseController
		def inthestudio
		end
	end
end

```

routes.rb
```
namespace :testing do
    localized do
      get 'in_the_studio', to: 'pages#inthestudio'
    end
  end
```

en.yml
```
en:
  routes:
    testing:
      in_the_studio: "in-the-studio"

```
fr.yml
```
fr:
  routes:
    testing:
      in_the_studio: "en-studio"
```

Unfortunately this doesn't work.
I tried reversing namespace and controller name in the yml files without success either.

How can this be achieved?

Thanks!
- Vincent
