### ISSUE TITLE
Problems to translate routes

### ISSUE THREAD

**Issue by phlegx** [enriclluelles/route_translator#169]
Hi! I have the following structure but I am not able to translate the routes:

# First example

```ruby
get '/address/ip', to: 'address#ip'
get '/address/ip/v4', to: 'address#ipv4'
get '/address/ip/v6', to: 'address#ipv6'
```

With the following translation yml:

```yml
en:
  routes:
    address: 'address-test'
    controllers:
        address:
          ip: ' ip-test'
          ip/v4: 'v4-test'
          ip/v6: 'v6-test'
```

should result in:

```
http://example.com/en/address-test/ip-test
http://example.com/en/address-test/ip-test/v4-test
http://example.com/en/address-test/ip-test/v6-test
```

results in:

```
http://example.com/en/address-test/ip-test
http://example.com/en/address-test/ip-test/v4
http://example.com/en/address-test/ip-test/v6
```

# Second example

```ruby
get '/address/ip', to: 'address#ip'        # controller Address, action ip
get '/address/ip/v4', to: 'address/ip#v4'  # controller Address::IpController, action v4
get '/address/ip/v6', to: 'address/ip#v6'  # controller Address::IpController, action v6
```

With the following translation yml:

```yml
en:
  routes:
    address: 'address-test'
    controllers:
        address:
          ip: 'ip-test'
            v4: 'v4-test' # not allowed, yml parser fails.
          ip/v4: 'v4-test' # don't work 
        address/ip:
          v4: 'v4-test'
          v6: 'v6-test'
```

should result in:

```
http://example.com/en/address-test/ip-test
http://example.com/en/address-test/ip-test/v4-test
http://example.com/en/address-test/ip-test/v6-test
```

results in:

```
http://example.com/en/address-test/ip-test
http://example.com/en/address-test/ip/v4
http://example.com/en/address-test/ip/v6
```

What can I do to solve this problem? The first URL is translated right, the others not.

**Comment by tagliala** [comment]
Hi,

sorry for the late reply

# First example

```yml
en:
  routes:
    address: 'address-test'
    controllers:
      address:
        ip: 'ip-test'
        v4: 'v4-test'
        v6: 'v6-test'
```

or

```yml
en:
  routes:
    address: 'address-test'
    ip: 'ip-test'
    v4: 'v4-test'
    v6: 'v6-test'
```


# Second example

```yml
en:
  routes:
    address: 'address-test'
    ip: 'ip-test'
    controllers:
      address:
        ip:
          v4: 'v4-test'
          v6: 'v6-test'
```

### Wait... this doesn't work!

Yes, it does not work. It's because you are using an action (`ip`) with the same name of a nested controller (`ip`),  so `I18n.translate('ip')` in the scope of `address` will return a hash `{ v4: .., v6: ...}` .

I don't know if I'm going to fix this, but meanwhile I'm going to close this request

Hope it helps
